# Generated by Django 4.1.1 on 2022-10-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github",
            field=models.URLField(blank=True),
        ),
    ]
